targets:
  $default:
    builders:
      generators|annotations:
        enabled: true

builders:
  generators:
    target: ":generators"
    import: "package:generators/generators.dart"
    builder_factories: ["generateJsonClass"]
    build_extentions: {".dart":  [".g.dart"]}
    auto_apply: dependets
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]